pipeline {
    //agent any
    agent{
        docker {
            image 'windsekirun/jenkins-android-docker:1.1.1'
        }
    }
stages{
        stage("build") {
            steps{
                sh "chmod +x gradlew"
                junit '**/TEST-*.xml'
                echo "The build test stage passed"
            }
        }
        stage("test") {
            steps{
                echo "The test stage passed 2"
            }
        }
    }
post{
        always{
            echo "Post build testing echo"
            // Clear
            cleanWs()  
        }
    }
}
