pipeline {
    //agent any
    agent{
        docker {
            image 'windsekirun/jenkins-android-docker:1.1.1'
        }
    }
    options {
        skipStagesAfterUnstable()
    }
    stages{
        stage("Pre build stage:") {
            steps{
                sh "chmod +x ./gradlew"
                echo "grant permission gradle."
            }
        }
        stage('Compiling stage:') {
            steps {
                sh './gradlew compileDebugSources'
                echo "compiling succeed."
            }
        }
        stage('Unit test') {
            steps {
                sh './gradlew testDebugUnitTest testDebugUnitTest' 
                echo "unitTesting succeed."
            }
        }
        stage('Build APK') {
          steps {
            sh './gradlew assembleDebug'
            //archiveArtifacts '**/*.apk'
          }
    }
        stage('Finished'){
            steps {
                echo 'Jenkins tests on the Git project finished running succesfully!'
            }
        }
    }
}
