pipeline {
    //agent any
    agent{
        docker {
            image 'windsekirun/jenkins-android-docker:1.1.1'
        }
    }
options {
    skipStagesAfterUnstable()
}
stages{
        stage("Prepare") {
            steps{
                sh "chmod +x ./gradlew"
                //junit '**/TEST-*.xml'
            }
        }
        stage('Compile') {
          steps {
            sh './gradlew compileDebugSources'
          }
        }
        stage('Unit test') {
          steps {
            sh './gradlew testDebugUnitTest testDebugUnitTest' 

          }
        }
        stage('Build APK') {
			steps {
				sh './gradlew assembleDebug'
			}
		}
	}
}
